.TH GOODBYE "1" "September 28th, 2023" "goodbye 0.5" "User Commands"
.SH NAME
goodbye - a simple program created to test GNU Autotools and Linux Packaging
.SH SYNOPSIS
.B goodbye
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Print a friendly, customizable goodbye message.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
Show the version information and exit
.TP
\fB\-t\fR, \fB\-\-traditional\fR
Use traditional goodbye
.TP
\fB\-g\fR \fB\fRTEXT\/\fR
Print a TEXT
.SH "REPORTING BUGS"
Report bugs to: gustavo.bacagine@protonmail.com
.SH COPYRIGHT
Copyright \(co 2021 - 2023 Gustavo Bacagine.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
The full documentation for
.B goodbye
is maintained as a Texinfo manual.  If the
.B info
and
.B goodbye
programs are properly installed at your site, the command

