.TH GOODBYE "1" "February 2021" "hello 0.1" "User Commands"
.SH NAME
goodbye - a simple program created to test Gnu Autotools and Linux Packaging
.SH SYNOPSIS
.B goodbye
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Print a friendly, customizable greeting.
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
display version information and exit
.TP
\fB\-t\fR, \fB\-\-traditional\fR
use traditional greeting
.TP
\fB\-g\fR \fB\fRTEXT\/\fR
use TEXT as the greeting message
.SH "ADDITIONAL INFORMATION"
See
.UR https://github.com/Bacagine/goodbye/blob/main/man/goodbye.x
man/hello.x
.UE
how to add addtional information to a manual page.
.SH "REPORTING BUGS"
Report bugs to: gustavo.bacagine@protonmail.com
.SH COPYRIGHT
Copyright \(co 2021 Gustavo Bacagine.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
The full documentation for
.B goodbye
is maintained as a Texinfo manual.  If the
.B info
and
.B goodbye
programs are properly installed at your site, the command
.IP
.B info goodbye
.PP
should give you access to the complete manual.
